version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: ["npm", "start"]
    ports:
      - "3000:3000"
